import { useState } from "react";
import { useStudentReport } from "@/hooks/useStudentReport";
import { ReportGeneratingState } from "./ReportGeneratingState";
import { UnderstandingScoreRing } from "./UnderstandingScoreRing";
import { TopicScoreList } from "./TopicScoreList";
import { KnowledgeGapCard } from "./KnowledgeGapCard";
import { RevisionFlashcards } from "./RevisionFlashcards";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Loader2, RefreshCw, Download } from "lucide-react";
import { Link } from "react-router-dom";
import { jsPDF } from "jspdf";

interface StudentReportPageProps {
  sessionId: string;
}

function scoreMessage(score: number) {
  if (score >= 80) return "Excellent session! You understood most of this.";
  if (score >= 60) return "Good session! A few areas to review.";
  if (score >= 40) return "Some challenging topics today — let's review.";
  return "Tough session — but that's okay! Let's fill the gaps.";
}

export function StudentReportPage({ sessionId }: StudentReportPageProps) {
  const { report, videoResults, status, isLoading, activeGapIndex, setActiveGap, fetchReport } =
    useStudentReport({ sessionId });
  const [exporting, setExporting] = useState(false);

  const exportPDF = async () => {
    if (!report) return;
    setExporting(true);
    try {
      const doc = new jsPDF();
      let y = 20;
      const lm = 14;
      const pw = 180;

      doc.setFontSize(16);
      doc.text("Your Class Report", lm, y); y += 8;
      doc.setFontSize(9);
      doc.text(`Generated by NewtonAI — ${new Date(report.generated_at).toLocaleString()}`, lm, y); y += 12;

      // Understanding Score
      doc.setFontSize(14);
      doc.text(`Understanding Score: ${report.understanding_score}%`, lm, y); y += 8;
      doc.setFontSize(9);
      doc.text(scoreMessage(report.understanding_score), lm, y, { maxWidth: pw }); y += 10;

      // Topic Scores
      if (report.topic_scores.length > 0) {
        doc.setFontSize(12); doc.text("Topic Breakdown", lm, y); y += 6;
        doc.setFontSize(9);
        report.topic_scores.forEach((t) => {
          if (y > 270) { doc.addPage(); y = 20; }
          doc.text(`${t.slide_title || `Slide ${t.slide_index + 1}`}: ${t.score}%`, lm, y); y += 5;
        });
        y += 4;
      }

      // Knowledge Gaps
      if (report.knowledge_gaps.length > 0) {
        doc.setFontSize(12); doc.text("Knowledge Gaps", lm, y); y += 6;
        doc.setFontSize(9);
        report.knowledge_gaps.forEach((g) => {
          if (y > 270) { doc.addPage(); y = 20; }
          doc.text(`[${g.severity.toUpperCase()}] ${g.topic}: ${g.gap_reason}`, lm, y, { maxWidth: pw }); y += 6;
        });
        y += 4;
      }

      // Flashcard count
      if (report.revision_flashcards.length > 0) {
        doc.setFontSize(10);
        doc.text(`${report.revision_flashcards.length} revision flashcards available in-app`, lm, y); y += 8;
      }

      doc.setFontSize(8);
      doc.text("Generated by NewtonAI — newtonai.site", lm, 285);
      doc.save(`student-report-${sessionId.slice(0, 8)}.pdf`);
    } catch (err) {
      console.error("PDF export failed:", err);
    } finally {
      setExporting(false);
    }
  };

  if (isLoading) {
    return (
      <div className="flex justify-center py-12">
        <Loader2 className="h-6 w-6 animate-spin" />
      </div>
    );
  }

  if (status === "generating" || status === "idle") {
    return <ReportGeneratingState role="student" />;
  }

  if (status === "failed") {
    return (
      <div className="flex flex-col items-center gap-3 py-12">
        <p className="text-sm text-destructive">Report generation failed</p>
        <Button variant="outline" size="sm" onClick={() => fetchReport()} className="gap-1.5">
          <RefreshCw className="w-3.5 h-3.5" /> Retry
        </Button>
      </div>
    );
  }

  if (!report) return null;

  const gaps = report.knowledge_gaps;
  const hasGaps = gaps.length > 0;

  return (
    <div className="space-y-4 pb-8">
      {/* Header */}
      <div className="flex items-center justify-between">
        <h2 className="text-xl font-bold">Your Class Report 📊</h2>
        <div className="flex items-center gap-2">
          <Button
            variant="outline"
            size="sm"
            className="text-xs h-7 gap-1.5"
            onClick={exportPDF}
            disabled={exporting}
          >
            {exporting ? <Loader2 className="h-3 w-3 animate-spin" /> : <Download className="h-3 w-3" />}
            Export
          </Button>
          <Link to={`/session-notes/${sessionId}`}>
            <Button variant="outline" size="sm" className="text-xs h-7">
              View Notes
            </Button>
          </Link>
        </div>
      </div>

      {/* Score Hero */}
      <Card className="border-border/50 bg-gradient-to-b from-primary/[0.07] to-transparent">
        <CardContent className="py-10 flex flex-col items-center gap-3 rounded-2xl">
          <UnderstandingScoreRing score={report.understanding_score} size="large" />
          <p className="text-sm text-center text-muted-foreground max-w-xs">
            {scoreMessage(report.understanding_score)}
          </p>
          <p className="text-xs text-muted-foreground">
            {hasGaps
              ? `${gaps.length} knowledge gap${gaps.length > 1 ? "s" : ""} identified`
              : "No gaps found! 🎉"}
          </p>
        </CardContent>
      </Card>

      {/* Topic Breakdown */}
      <TopicScoreList topicScores={report.topic_scores} />

      {/* Revision Flashcards */}
      {report.revision_flashcards.length > 0 && (
        <RevisionFlashcards flashcards={report.revision_flashcards} />
      )}

      {/* Knowledge Gaps */}
      {hasGaps ? (
        <div className="space-y-2">
          <p className="text-sm font-semibold">📚 Topics to Review</p>
          {gaps.map((gap, i) => {
            const gapFlashcards = report.revision_flashcards.filter(
              (fc) => fc.slide_index === gap.slide_index
            );
            const video = videoResults.find((v) => v.topic === gap.topic) ?? null;
            const isExpanded = activeGapIndex === null
              ? i === gaps.findIndex((g) => g.severity === "high") || (i === 0 && !gaps.some((g) => g.severity === "high"))
              : activeGapIndex === i;

            return (
              <KnowledgeGapCard
                key={i}
                gap={gap}
                flashcards={gapFlashcards}
                videoResult={video}
                isExpanded={isExpanded}
                onToggle={() => setActiveGap(isExpanded ? null : i)}
              />
            );
          })}
        </div>
      ) : (
        <Card className="border-border/50 border-green-500/20">
          <CardContent className="py-6 text-center space-y-2">
            <p className="text-lg">🎉 Great work!</p>
            <p className="text-sm text-muted-foreground">No knowledge gaps detected.</p>
            <p className="text-xs text-muted-foreground">You can still review your session notes:</p>
            <Link to={`/session-notes/${sessionId}`}>
              <Button variant="outline" size="sm" className="text-xs mt-1">
                View Session Notes →
              </Button>
            </Link>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
