import { useState, useEffect } from "react";
import { useTeacherReport } from "@/hooks/useTeacherReport";
import { ReportGeneratingState } from "./ReportGeneratingState";
import { EngagementHeatmap } from "./EngagementHeatmap";
import { TopicsToRevisitCard } from "./TopicsToRevisitCard";
import { ConceptCheckReportCard } from "./ConceptCheckReportCard";
import { UnansweredQuestionsCard } from "./UnansweredQuestionsCard";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Loader2, RefreshCw, Download } from "lucide-react";
import { jsPDF } from "jspdf";

interface TeacherReportPageProps {
  sessionId: string;
}

export function TeacherReportPage({ sessionId }: TeacherReportPageProps) {
  const { report, classOverview, status, isLoading, error, triggerGeneration, fetchClassOverview } =
    useTeacherReport({ sessionId });
  const [exporting, setExporting] = useState(false);

  // Fetch class overview when report is ready
  useEffect(() => {
    if (status === "ready" && !classOverview) {
      fetchClassOverview();
    }
  }, [status, classOverview, fetchClassOverview]);

  const exportReportAsPDF = async () => {
    if (!report?.teacher_report) return;
    setExporting(true);
    try {
      const tr = report.teacher_report;
      const doc = new jsPDF();
      let y = 20;
      const lm = 14;
      const pw = 180;

      doc.setFontSize(16);
      doc.text("Class Intelligence Report", lm, y); y += 8;
      doc.setFontSize(9);
      doc.text(`Generated by NewtonAI — ${new Date(report.generated_at).toLocaleString()}`, lm, y); y += 10;

      // Session Summary
      doc.setFontSize(12); doc.text("Session Summary", lm, y); y += 6;
      doc.setFontSize(9);
      doc.text(`Duration: ${tr.session_summary.duration_minutes} min | Students: ${tr.session_summary.active_students}/${tr.session_summary.total_students} | Engagement: ${Math.round(tr.session_summary.engagement_rate)}%`, lm, y); y += 10;

      // Topics to Revisit
      if (tr.topics_to_revisit.length > 0) {
        doc.setFontSize(12); doc.text("Topics to Revisit", lm, y); y += 6;
        doc.setFontSize(9);
        tr.topics_to_revisit.forEach((t) => {
          if (y > 270) { doc.addPage(); y = 20; }
          doc.text(`[${t.priority.toUpperCase()}] ${t.topic}: ${t.reason}`, lm, y, { maxWidth: pw }); y += 6;
        });
        y += 4;
      }

      // Concept Checks
      if (tr.concept_check_analysis.length > 0) {
        doc.setFontSize(12); doc.text("Concept Check Summary", lm, y); y += 6;
        doc.setFontSize(9);
        tr.concept_check_analysis.forEach((c) => {
          if (y > 270) { doc.addPage(); y = 20; }
          doc.text(`${c.question.slice(0, 60)}... — ${Math.round(c.correct_percentage)}% correct${c.needs_review ? " ⚠️" : ""}`, lm, y, { maxWidth: pw }); y += 5;
        });
        y += 4;
      }

      // Unanswered Questions
      if (tr.top_unanswered_questions.length > 0) {
        doc.setFontSize(12); doc.text("Top Unanswered Questions", lm, y); y += 6;
        doc.setFontSize(9);
        tr.top_unanswered_questions.forEach((q) => {
          if (y > 270) { doc.addPage(); y = 20; }
          doc.text(`[▲${q.upvotes}] ${q.content}`, lm, y, { maxWidth: pw }); y += 5;
        });
        y += 4;
      }

      // Engagement per slide
      if (tr.engagement_heatmap.length > 0) {
        if (y > 240) { doc.addPage(); y = 20; }
        doc.setFontSize(12); doc.text("Engagement Per Slide", lm, y); y += 6;
        doc.setFontSize(8);
        doc.text("Slide | Title | Score | Pulse | Notes | Questions", lm, y); y += 4;
        tr.engagement_heatmap.forEach((h) => {
          if (y > 270) { doc.addPage(); y = 20; }
          doc.text(`${h.slide_index + 1} | ${(h.slide_title || "").slice(0, 30)} | ${Math.round(h.engagement_score)} | ${h.pulse_responses} | ${h.annotations} | ${h.questions_asked}`, lm, y); y += 4;
        });
        y += 4;
      }

      // Student Distribution
      if (classOverview) {
        if (y > 250) { doc.addPage(); y = 20; }
        doc.setFontSize(12); doc.text("Student Score Distribution", lm, y); y += 6;
        doc.setFontSize(9);
        const d = classOverview.score_distribution;
        doc.text(`Excellent (80-100): ${d.excellent} | Good (60-79): ${d.good} | Needs Work (40-59): ${d.needs_work} | Struggling (0-39): ${d.struggling}`, lm, y, { maxWidth: pw }); y += 8;
      }

      // Footer
      doc.setFontSize(8);
      doc.text("Generated by NewtonAI — newtonai.site", lm, 285);

      doc.save(`intelligence-report-${sessionId.slice(0, 8)}.pdf`);
    } catch (err) {
      console.error("PDF export failed:", err);
    } finally {
      setExporting(false);
    }
  };

  if (isLoading) {
    return (
      <div className="flex justify-center py-12">
        <Loader2 className="h-6 w-6 animate-spin" />
      </div>
    );
  }

  if (status === "generating" || status === "idle") {
    return <ReportGeneratingState role="teacher" />;
  }

  if (status === "failed") {
    return (
      <div className="flex flex-col items-center gap-3 py-12">
        <p className="text-sm text-destructive">Report generation failed</p>
        <Button variant="outline" size="sm" onClick={triggerGeneration} className="gap-1.5">
          <RefreshCw className="w-3.5 h-3.5" /> Retry
        </Button>
      </div>
    );
  }

  const tr = report?.teacher_report;
  if (!tr) return null;

  const distrib = classOverview?.score_distribution;

  return (
    <div className="space-y-4 pb-8">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-xl font-bold">📊 Class Intelligence Report</h2>
          <p className="text-xs text-muted-foreground">Generated by NewtonAI</p>
        </div>
        <Button variant="outline" size="sm" className="gap-1.5 text-xs" onClick={exportReportAsPDF} disabled={exporting}>
          {exporting ? <Loader2 className="h-3 w-3 animate-spin" /> : <Download className="h-3 w-3" />}
          Export PDF
        </Button>
      </div>

      {/* Session Summary */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-2">
        {[
          { label: "Duration", value: `${tr.session_summary.duration_minutes} min` },
          { label: "Students", value: `${tr.session_summary.active_students}/${tr.session_summary.total_students}` },
          { label: "Engagement", value: `${Math.round(tr.session_summary.engagement_rate)}%` },
          { label: "Class Avg", value: classOverview ? `${Math.round(classOverview.class_average_score)}%` : "—" },
        ].map((s) => (
          <Card key={s.label} className="border-border/50">
            <CardContent className="p-3 text-center">
              <p className="text-lg font-bold">{s.value}</p>
              <p className="text-[10px] text-muted-foreground">{s.label}</p>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Engagement Heatmap */}
      <EngagementHeatmap
        heatmapData={tr.engagement_heatmap}
        totalSlides={tr.engagement_heatmap.length}
      />

      {/* Topics to Revisit */}
      <TopicsToRevisitCard topics={tr.topics_to_revisit} aiFailed={tr._ai_failed} />

      {/* Concept Checks + Unanswered Questions */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <ConceptCheckReportCard analysis={tr.concept_check_analysis} />
        <UnansweredQuestionsCard questions={tr.top_unanswered_questions} />
      </div>

      {/* Student Overview */}
      {classOverview && distrib && (
        <Card className="border-border/50">
          <CardContent className="p-4 space-y-3">
            <p className="text-sm font-semibold">How your class performed</p>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-2">
              {[
                { label: "Excellent (80-100)", count: distrib.excellent, color: "bg-green-500/15 text-green-400 border-green-500/30" },
                { label: "Good (60-79)", count: distrib.good, color: "bg-teal-500/15 text-teal-400 border-teal-500/30" },
                { label: "Needs Work (40-59)", count: distrib.needs_work, color: "bg-amber-500/15 text-amber-400 border-amber-500/30" },
                { label: "Struggling (0-39)", count: distrib.struggling, color: "bg-red-500/15 text-red-400 border-red-500/30" },
              ].map((d) => (
                <div key={d.label} className={`rounded-lg border p-2.5 text-center ${d.color}`}>
                  <p className="text-lg font-bold">{d.count}</p>
                  <p className="text-[9px]">{d.label}</p>
                </div>
              ))}
            </div>
            <div className="flex flex-col gap-1 text-xs">
              <span className="text-green-400">✓ {classOverview.strongest_topic.slide_title} — avg {Math.round(classOverview.strongest_topic.avg_score)}%</span>
              <span className="text-amber-400">⚠️ {classOverview.weakest_topic.slide_title} — avg {Math.round(classOverview.weakest_topic.avg_score)}%</span>
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
