import { Video, Headphones, Gift, Brain, FileText, Mic, PenTool, Sparkles, DollarSign, Globe } from "lucide-react";

export const competitors = {
  chegg: {
    name: "Chegg",
    slug: "chegg",
    tagline: "Homework help and textbook solutions",
    logo: "📚",
    monthlyPrice: "$15.95",
    yearlyPrice: "$95.40",
    pricePerMonth: 15.95,
    strengths: [
      "Expert Q&A responses",
      "Textbook solutions library",
      "Math solver tool",
      "Writing assistance",
    ],
    weaknesses: [
      "No AI-generated flashcards",
      "No video integration in reading",
      "No podcast generation",
      "Expensive monthly subscription",
      "No free tier available",
      "Single-purpose platform",
    ],
    verdict: "Chegg excels at textbook solutions but lacks modern AI study tools. NewtonAI offers 7 AI tools at nearly half the price.",
  },
  quizlet: {
    name: "Quizlet",
    slug: "quizlet",
    tagline: "Digital flashcards and study sets",
    logo: "🎴",
    monthlyPrice: "$7.99",
    yearlyPrice: "$35.99",
    pricePerMonth: 7.99,
    strengths: [
      "Large flashcard library",
      "Learn mode with spaced repetition",
      "Community-created study sets",
      "Mobile app experience",
    ],
    weaknesses: [
      "No PDF integration or reader",
      "No AI homework help",
      "No video search or embedding",
      "Limited AI generation capabilities",
      "No podcast or audio learning",
      "No handwriting recognition",
    ],
    verdict: "Quizlet is great for pre-made flashcards, but NewtonAI generates them from any content with videos and AI explanations.",
  },
  studocu: {
    name: "Studocu",
    slug: "studocu",
    tagline: "Study documents and notes sharing",
    logo: "📝",
    monthlyPrice: "$9.99",
    yearlyPrice: "$47.88",
    pricePerMonth: 9.99,
    strengths: [
      "Large student document library",
      "Course-specific study guides",
      "Exam preparation materials",
      "University-focused content",
    ],
    weaknesses: [
      "No AI content generation",
      "No video integration",
      "No podcast feature",
      "Relies entirely on user uploads",
      "No interactive study tools",
      "No homework solving",
    ],
    verdict: "Studocu offers shared notes, but NewtonAI creates personalized study materials with AI from any document you upload.",
  },
  "course-hero": {
    name: "Course Hero",
    slug: "course-hero",
    tagline: "Study resources and tutoring",
    logo: "🎓",
    monthlyPrice: "$14.95",
    yearlyPrice: "$119.40",
    pricePerMonth: 14.95,
    strengths: [
      "24/7 tutor access",
      "Large document library",
      "Practice problems",
      "Course-specific resources",
    ],
    weaknesses: [
      "Very expensive subscription",
      "No AI podcast generation",
      "No flashcard auto-generation",
      "No video in document reader",
      "No voice transcription",
      "Limited free access",
    ],
    verdict: "Course Hero charges premium prices for document access. NewtonAI provides AI-powered tools that create study materials for you.",
  },
  chatgpt: {
    name: "ChatGPT",
    slug: "chatgpt",
    tagline: "General-purpose AI assistant",
    logo: "🤖",
    monthlyPrice: "$20",
    yearlyPrice: "$240",
    pricePerMonth: 20,
    strengths: [
      "Versatile AI capabilities",
      "Code generation",
      "Creative writing",
      "General knowledge",
    ],
    weaknesses: [
      "Not study-focused",
      "No flashcard system or spaced repetition",
      "No integrated PDF reader",
      "No video search or embedding",
      "No progress tracking",
      "No structured study tools",
    ],
    verdict: "ChatGPT is a general AI, not a study platform. NewtonAI is purpose-built for learning with 7 specialized study tools.",
  },
};

export const newtonFeatures = {
  name: "NewtonAI",
  monthlyPrice: "$8.49",
  yearlyPrice: "$78",
  pricePerMonth: 8.49,
  tagline: "AI-Powered Study Platform",
  uniqueFeatures: [
    {
      title: "Videos Inside Your PDF",
      description: "Search any topic and watch educational videos directly embedded in your PDF reader. No tab switching needed.",
      icon: Video,
    },
    {
      title: "Free Tier with Ads",
      description: "Access all features for free with optional video ads. No credit card required to get started.",
      icon: Gift,
    },
    {
      title: "AI-Generated Podcasts",
      description: "Transform any document, YouTube video, or notes into an engaging audio podcast for learning on the go.",
      icon: Headphones,
    },
    {
      title: "7 AI Tools in One",
      description: "Flashcards, Quizzes, Summaries, Mind Maps, Lecture Notes, Podcasts, and Homework Help - all powered by AI.",
      icon: Brain,
    },
    {
      title: "Multi-Source Input",
      description: "Upload PDFs, paste YouTube links, type text, record voice, or snap photos of handwritten notes.",
      icon: FileText,
    },
    {
      title: "Voice Transcription",
      description: "Record lectures and get instant AI transcription with smart formatting and key point extraction.",
      icon: Mic,
    },
    {
      title: "Handwriting OCR",
      description: "Google Lens-style recognition for handwritten notes. Snap a photo and convert to digital text instantly.",
      icon: PenTool,
    },
    {
      title: "Smart Study Tracking",
      description: "Track your study sessions, quiz scores, and learning progress across all subjects.",
      icon: Sparkles,
    },
  ],
};

export const featureComparison = [
  { feature: "Videos in PDF Reader", newton: true, chegg: false, quizlet: false, studocu: false, "course-hero": false, chatgpt: false },
  { feature: "AI Flashcard Generation", newton: true, chegg: false, quizlet: "Limited", studocu: false, "course-hero": false, chatgpt: "Manual" },
  { feature: "AI Quiz Generator", newton: true, chegg: false, quizlet: true, studocu: false, "course-hero": false, chatgpt: "Manual" },
  { feature: "AI Podcast Creation", newton: true, chegg: false, quizlet: false, studocu: false, "course-hero": false, chatgpt: false },
  { feature: "Mind Map Generator", newton: true, chegg: false, quizlet: false, studocu: false, "course-hero": false, chatgpt: "Manual" },
  { feature: "AI Homework Help", newton: true, chegg: true, quizlet: false, studocu: false, "course-hero": true, chatgpt: true },
  { feature: "PDF Reader", newton: true, chegg: false, quizlet: false, studocu: true, "course-hero": true, chatgpt: false },
  { feature: "Voice Transcription", newton: true, chegg: false, quizlet: false, studocu: false, "course-hero": false, chatgpt: true },
  { feature: "Handwriting OCR", newton: true, chegg: false, quizlet: false, studocu: false, "course-hero": false, chatgpt: false },
  { feature: "Free Tier", newton: "Yes (with ads)", chegg: false, quizlet: "Limited", studocu: "Limited", "course-hero": false, chatgpt: "Limited" },
  { feature: "Starting Price", newton: "$8.49/mo", chegg: "$15.95/mo", quizlet: "$7.99/mo", studocu: "$9.99/mo", "course-hero": "$14.95/mo", chatgpt: "$20/mo" },
];

export type CompetitorKey = keyof typeof competitors;
